### ISSUE TITLE
Bower Availability

### ISSUE THREAD

**Issue by evilkermit** [Sumbera/gLayers.Leaflet#1]
Hi! I have a project which is currently making use of this plugin (well, the old Gist, but I'm updating this today), and we are using Bower to manage our dependencies with the exception of this one.

I was using a modified version to work with Leaflet 1.0.0-rc1, but since you've just handled this yourself, I was wondering if you'd be willing to make it available on Bower so we don't have to keep a modified copy of it.

If needed, I am willing to help with this.

**Comment by Sumbera** [comment]
Hi, sounds great, I would appreciate your help with Bower, few notes - I plan to one more rename this project to gLayers.Leaflet  and there might be more layers included in the future like tiled canvas or svg (cca 4 more classesor so ) related to Leaflet only.

**Comment by evilkermit** [comment]
I just submitted a pull request with a basic bower.json for the project. If everything is ok with it, then once merged in you would need to do two things:
1. Tag the repo: `git tag v1.0.0` and `git push origin --tags`
2. Register with `bower register`: https://bower.io/docs/creating-packages/#register

If you update the project in the future with more layer types, then you should be able to add the JS files corresponding to the new layers to the main list in bower.json, bump the version number in bower.json, and tag the repo with the new version number (bower should automatically pick up the new version once you push the tag to GitHub).

**Comment by Sumbera** [comment]
thanks for 262bd38  and the  steps to publish, should be ready in bower now.

**Comment by evilkermit** [comment]
I gave it a try and everything seems to be working. Thanks for your help!
