### ISSUE TITLE
can not find lat/lon in geojson file

### ISSUE THREAD

**Issue by soli004** [Sumbera/gLayers.Leaflet#12]
Hello,

Tried the basic script, but can not load the geojson file as it "Cannot read the 'lat' of undefined"
even if I had put the correct (d[13], d[14]). I had to strip all of the data and leave only the lat/lon coordinates similar to the demo file "data.js", then I could make it work.
What is the right way to make it work with geojson file with features and properties?

Short sample of the file:

var data = [{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "sid": 20001, "name": "Click", "zipcode": 17777, "city": "Copenhagen", "address": "Tierra road 22", "concept": "Collect", "district": "north2", "date": "2015-03-29", "id_1": "-", "id_2": "-", "id_ 3": "-", "id_4": "-" }, "geometry": { "type": "Point", "coordinates": [ 16.009999329396344, 52.349344871491816 ] } },];
Thanks
`    <script src="js/L.CanvasLayer.js"></script>
    
    <script src="ssd.js" charset="utf-8"></script>

    <script>
        var points = data; // data loaded from data.js
        var leafletMap = L.map('map').setView([59.50, 14.54], 5);
        // -- pls change your key to keep this working for others.
        L.tileLayer("https://{s}.tiles.mapbox.com/v4/mapbox.dark/{z}/{x}/{y}@2x.png?access_token=pk.eyJ1Ijoic29saTAwNCIsImEiOiJjamM2aWhxMDIwb2RqMnhtcXlmYWE4NXQwIn0.-M6W-0nVuhQv3AEIPMlJqA")
            .addTo(leafletMap);
        L.canvasLayer()
            .delegate(this) // -- if we do not inherit from L.CanvasLayer we can setup a delegate to receive events from L.CanvasLayer
            .addTo(leafletMap);
      
        function onDrawLayer(info) {
            var ctx = info.canvas.getContext('2d');
            ctx.clearRect(0, 0, info.canvas.width, info.canvas.height);
            ctx.fillStyle = "rgba(255,116,0, 0.5)";
            for (var i = 0; i < data.length; i++) {
                var d = data[i];
                if (info.bounds.contains([d[13], d[14]])) {
                    dot = info.layer._map.latLngToContainerPoint([d[13], d[14]]);
                    ctx.beginPath();
                    ctx.arc(dot.x, dot.y, 3, 0, Math.PI * 2);
                    ctx.fill();
                    ctx.closePath();
                }
            }
        };`

**Comment by soli004** [comment]
Removed the "[&]" in the beginning and the end of .js file, error gone but no visible points... any hint what is wrong? Updated js file below...
`var data = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "sid": 20001, "name": "Click", "zipcode": 17777, "city": "Copenhagen", "address": "Tierra road 22", "concept": "Collect", "district": "north2", "date": "2015-03-29", "id_1": "-", "id_2": "-", "id_ 3": "-", "id_4": "-" }, "geometry": { "type": "Point", "coordinates": [ 16.009999329396344, 52.349344871491816 ] } };`

**Comment by Sumbera** [comment]
this is parsing problem of json
