### ISSUE TITLE
Method _animateZoom wrong calculate offset for L.CRS.Simple

### ISSUE THREAD

**Issue by peterkarabinovic** [Sumbera/gLayers.Leaflet#6]
With leaflet >= 1.0.0 and with planar coods system (`L.CRS.Simple`) method `_animateZoom` calculate offset for animation not correctly like this:

```javascript
this._map._latLngToNewLayerPoint(this._map.getBounds().getNorthWest(), e.zoom, e.center)
```
but `getNorthWest()` point to bottom left corner. Better way calculate like this  

```javascript
this._map._latLngBoundsToNewLayerBounds(this._map.getBounds(), e.zoom, e.center).min;
```

This works both with geo and with planar CRS

**Comment by Sumbera** [comment]
thanks ! fixed.
